const fs = require('fs');

const COMPONENTS_PATH = './src/components';
const isDirectory = name => fs.lstatSync(`${COMPONENTS_PATH}/${name}`).isDirectory();

const componentNames = fs.readdirSync(COMPONENTS_PATH).filter(isDirectory);

let main = componentNames.map(name => `require('./components/${name}.js');`).join('\n');
main = `// This file was automatically generated by "build.js"\n${main}`

fs.writeFileSync('./dist/index.js', main);
